version: "3"
services:
    api:
        container_name: tris-api
        build: ./Api
        ports:
            - "5000:80"
    client:
        container_name: tris-client
        build: ./Client
        ports:
            - "5001:80"
